let brands = [
  { img: "./src/assets/images/brands/pril.png" },
  { img: "./src/assets/images/brands/persil.png" },
  { img: "./src/assets/images/brands/kingstar.png" },
  { img: "./src/assets/images/brands/sp.png" },
  { img: "./src/assets/images/brands/huawei.png" },
  { img: "./src/assets/images/brands/pakshoma.png" },
  { img: "./src/assets/images/brands/cheshme.jpg" },
  { img: "./src/assets/images/brands/samsung.jpg" },
  { img: "./src/assets/images/brands/bioaqua.png" },
  { img: "./src/assets/images/brands/kale.png" },
  { img: "./src/assets/images/brands/xiaomi.png" },
  { img: "./src/assets/images/brands/my.png" },
  { img: "./src/assets/images/brands/pril.png" },
  { img: "./src/assets/images/brands/persil.png" },
  { img: "./src/assets/images/brands/kingstar.png" },
  { img: "./src/assets/images/brands/sp.png" },
  { img: "./src/assets/images/brands/huawei.png" },
  { img: "./src/assets/images/brands/pakshoma.png" },
  { img: "./src/assets/images/brands/cheshme.jpg" },
  { img: "./src/assets/images/brands/samsung.jpg" },
  { img: "./src/assets/images/brands/bioaqua.png" },
  { img: "./src/assets/images/brands/kale.png" },
  { img: "./src/assets/images/brands/xiaomi.png" },
  { img: "./src/assets/images/brands/my.png" },
];

export default brands;

export let berandsName = [
  ["نوری تازه", "NORITAZEH"],
  ["ام جی اس", "MGS"],
  ["دینو", "Dino"],
  ["چینی زرین ایران", "Zarin Iran Porcelain Inds"],
  ["نورینو", "noorino"],
  ["یونیک", "Unique"],
  ["صنایع استیل ایران", "Sanaye Steel Iran"],
  ["بلینک مکس", "Blink Max"],
  ["وینتج", "Vintage"],
  ["بوهمیا", "Bohemia"],
  ["ساکورا", "Sakura"],
  ["بلور کاوه", "Kaveh Crystal"],
  ["سیلویا", "Silvia"],
  ["لومینارک", "Luminarc"],
  ["لاکی", "Lucky"],
  ["اویز", "Eviz"],
  ["درنیکا", "DORNIKA"],
  ["ریور", "River"],
  ["ایکیا", "Ikea"],
  ["رایکا", "RAIKA"],
  ["دبلیو ام اف", "WMF"],
  ["تاپ چویس", "Topchoice"],
  ["لیمون", "limon"],
  ["ایرنا", "IRENA"],
  ["پارس اپال", "Pars opal"],
  ["لاو", "LAV"],
  ["متفرقه", "Miscellaneous"],
  ["آیروپال", "Iropal"],
  ["وون", "WOON"],
  ["جی فی نی", "GIFFINI"],
  ["مستر راد", "Mr Rad"],
  ["گلاسگو", "GLASGO"],
  ["اف جی تی", "FGT"],
  ["ساکورا", "Sakura"],
  ["فرش استایل", "Fresh style"],
  ["بی ام دی !", "BMD!"],
  ["لاژید", "Lazhid"],
  ["کمی", "Kemey"],
  ["کازیوه", "Kaziveh"],
  ["چاپریکا", "Chaprika"],
];
